var hierarchy =
[
    [ "AXOS::kernels::blas_detail::Accumulate< T, MR, NV >", "structAXOS_1_1kernels_1_1blas__detail_1_1Accumulate.html", null ],
    [ "AXOS::kernels::blas_detail::Accumulate< T, 4, 2 >", "structAXOS_1_1kernels_1_1blas__detail_1_1Accumulate_3_01T_00_014_00_012_01_4.html", null ],
    [ "AXOS::kernels::blas_detail::Accumulate< T, 6, 2 >", "structAXOS_1_1kernels_1_1blas__detail_1_1Accumulate_3_01T_00_016_00_012_01_4.html", null ],
    [ "AXOS::kernels::blas_detail::Accumulate< T, 8, 3 >", "structAXOS_1_1kernels_1_1blas__detail_1_1Accumulate_3_01T_00_018_00_013_01_4.html", null ],
    [ "AXOS::detail::op::Add", "structAXOS_1_1detail_1_1op_1_1Add.html", null ],
    [ "AXOS::Solver::qp::qipm::AddDiag", "structAXOS_1_1Solver_1_1qp_1_1qipm_1_1AddDiag.html", null ],
    [ "AXOS::Solver::qp::qipm::AddVec", "structAXOS_1_1Solver_1_1qp_1_1qipm_1_1AddVec.html", null ],
    [ "AXOS::Sparse::dense::packed::Aligned", "structAXOS_1_1Sparse_1_1dense_1_1packed_1_1Aligned.html", null ],
    [ "AXOS::Solver::pdlp::AvgM", "structAXOS_1_1Solver_1_1pdlp_1_1AvgM.html", null ],
    [ "AXOS::Solver::pdlp::AvgN", "structAXOS_1_1Solver_1_1pdlp_1_1AvgN.html", null ],
    [ "AXOS::Solver::ipm::Axpy", "structAXOS_1_1Solver_1_1ipm_1_1Axpy.html", null ],
    [ "AXOS::Cpu::Backend", "structAXOS_1_1Cpu_1_1Backend.html", null ],
    [ "AXOS::Cuda::Backend", "structAXOS_1_1Cuda_1_1Backend.html", null ],
    [ "AXOS::backend_of< X, class >", "structAXOS_1_1backend__of.html", null ],
    [ "AXOS::backend_of< X, std::void_t< typename X::backend_type > >", "structAXOS_1_1backend__of_3_01X_00_01std_1_1void__t_3_01typename_01X_1_1backend__type_01_4_01_4.html", null ],
    [ "AXOS::Solver::BasisFactor", "classAXOS_1_1Solver_1_1BasisFactor.html", null ],
    [ "AXOS::Sparse::MultifrontalLdl< T, Idx >::Block", "structAXOS_1_1Sparse_1_1MultifrontalLdl_1_1Block.html", null ],
    [ "AXOS::kernels::blas_detail::Blocking< T >", "structAXOS_1_1kernels_1_1blas__detail_1_1Blocking.html", null ],
    [ "AXOS::Solver::milp::BranchAndBound", "classAXOS_1_1Solver_1_1milp_1_1BranchAndBound.html", null ],
    [ "AXOS::Solver::ipm::BuildG", "structAXOS_1_1Solver_1_1ipm_1_1BuildG.html", null ],
    [ "AXOS::Solver::ipm::BuildTheta", "structAXOS_1_1Solver_1_1ipm_1_1BuildTheta.html", null ],
    [ "AXOS::Solver::milp::CmirSeparator", "classAXOS_1_1Solver_1_1milp_1_1CmirSeparator.html", null ],
    [ "AXOS::Solver::BasisFactor::Column", "structAXOS_1_1Solver_1_1BasisFactor_1_1Column.html", null ],
    [ "AXOS::Solver::ipm::CompAff", "structAXOS_1_1Solver_1_1ipm_1_1CompAff.html", null ],
    [ "AXOS::Solver::ipm::CompCorr", "structAXOS_1_1Solver_1_1ipm_1_1CompCorr.html", null ],
    [ "AXOS::Sparse::CooBuilder< T, Idx >", "classAXOS_1_1Sparse_1_1CooBuilder.html", null ],
    [ "AXOS::Solver::pdlp::Copy", "structAXOS_1_1Solver_1_1pdlp_1_1Copy.html", null ],
    [ "axos_qp::Copy", "structaxos__qp_1_1Copy.html", null ],
    [ "AXOS::Solver::qp::CpuBackend", "classAXOS_1_1Solver_1_1qp_1_1CpuBackend.html", null ],
    [ "AXOS::Sparse::Csr< T, Idx, Store >", "classAXOS_1_1Sparse_1_1Csr.html", null ],
    [ "AXOS::Sparse::Csr< double, int32_t, Cpu::HostStorage >", "classAXOS_1_1Sparse_1_1Csr.html", null ],
    [ "AXOS::Solver::qp::CudaBackend", "classAXOS_1_1Solver_1_1qp_1_1CudaBackend.html", null ],
    [ "AXOS::Cuda::CudaStorage< T >", "classAXOS_1_1Cuda_1_1CudaStorage.html", null ],
    [ "AXOS::Cuda::CudaStorage< double >", "classAXOS_1_1Cuda_1_1CudaStorage.html", null ],
    [ "AXOS::Cuda::CudaStorage< int32_t >", "classAXOS_1_1Cuda_1_1CudaStorage.html", null ],
    [ "AXOS::Solver::milp::Cut", "structAXOS_1_1Solver_1_1milp_1_1Cut.html", null ],
    [ "AXOS::Solver::milp::gpu::DBuf< T >", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1DBuf.html", null ],
    [ "AXOS::Solver::milp::gpu::DBuf< double >", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1DBuf.html", null ],
    [ "AXOS::Solver::milp::gpu::DBuf< int >", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1DBuf.html", null ],
    [ "AXOS::Solver::milp::gpu::DBuf< int32_t >", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1DBuf.html", null ],
    [ "AXOS::Solver::milp::gpu::DBuf< long long >", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1DBuf.html", null ],
    [ "AXOS::Solver::milp::gpu::DBuf< unsigned >", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1DBuf.html", null ],
    [ "AXOS::Solver::milp::gpu::DBuf< unsigned char >", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1DBuf.html", null ],
    [ "AXOS::Solver::milp::gpu::DBuf< unsigned long long >", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1DBuf.html", null ],
    [ "AXOS::Solver::qp::DenormalGuard", "structAXOS_1_1Solver_1_1qp_1_1DenormalGuard.html", null ],
    [ "AXOS::Sparse::detail::DeviceCache", "structAXOS_1_1Sparse_1_1detail_1_1DeviceCache.html", [
      [ "AXOS::Sparse::cuda_detail::CusparseCache", "structAXOS_1_1Sparse_1_1cuda__detail_1_1CusparseCache.html", null ]
    ] ],
    [ "AXOS::Solver::milp::gpu::DeviceProblem", "structAXOS_1_1Solver_1_1milp_1_1gpu_1_1DeviceProblem.html", null ],
    [ "axos_qp::Diff", "structaxos__qp_1_1Diff.html", null ],
    [ "AXOS::Solver::pdlp::DiffSq", "structAXOS_1_1Solver_1_1pdlp_1_1DiffSq.html", null ],
    [ "axos_qp::DiffSq", "structaxos__qp_1_1DiffSq.html", null ],
    [ "AXOS::Domain< DIM >::Dim", "structAXOS_1_1Domain_1_1Dim.html", null ],
    [ "AXOS::detail::op::Div", "structAXOS_1_1detail_1_1op_1_1Div.html", null ],
    [ "AXOS::Domain< DIM >", "classAXOS_1_1Domain.html", null ],
    [ "AXOS::Solver::qp::qipm::Dot", "structAXOS_1_1Solver_1_1qp_1_1qipm_1_1Dot.html", null ],
    [ "axos_qp::Dot2", "structaxos__qp_1_1Dot2.html", null ],
    [ "AXOS::Solver::pdlp::DualRayM", "structAXOS_1_1Solver_1_1pdlp_1_1DualRayM.html", null ],
    [ "AXOS::Solver::pdlp::DualRayN", "structAXOS_1_1Solver_1_1pdlp_1_1DualRayN.html", null ],
    [ "AXOS::Solver::DualSimplex", "classAXOS_1_1Solver_1_1DualSimplex.html", null ],
    [ "AXOS::ElimOp< T >", "structAXOS_1_1ElimOp.html", null ],
    [ "AXOS::la_detail::PermCache< T >::Entry", "structAXOS_1_1la__detail_1_1PermCache_1_1Entry.html", null ],
    [ "AXOS::Expr< T, E >", "structAXOS_1_1Expr.html", null ],
    [ "AXOS::Expr< T, BinaryExpr< T, L, R, Op > >", "structAXOS_1_1Expr.html", [
      [ "AXOS::BinaryExpr< T, L, R, Op >", "classAXOS_1_1BinaryExpr.html", null ]
    ] ],
    [ "AXOS::Expr< T, MatMulExpr< T, SA, SB > >", "structAXOS_1_1Expr.html", [
      [ "AXOS::MatMulExpr< T, SA, SB >", "classAXOS_1_1MatMulExpr.html", null ]
    ] ],
    [ "AXOS::Expr< T, ScalarExpr< T, E, Op, Left > >", "structAXOS_1_1Expr.html", [
      [ "AXOS::ScalarExpr< T, E, Op, Left >", "classAXOS_1_1ScalarExpr.html", null ]
    ] ],
    [ "AXOS::Expr< T, UnaryExpr< T, E, F > >", "structAXOS_1_1Expr.html", [
      [ "AXOS::UnaryExpr< T, E, F >", "classAXOS_1_1UnaryExpr.html", null ]
    ] ],
    [ "AXOS::detail::op::Fabs", "structAXOS_1_1detail_1_1op_1_1Fabs.html", null ],
    [ "std::false_type", null, [
      [ "AXOS::Sparse::is_complex_value< T >", "structAXOS_1_1Sparse_1_1is__complex__value.html", null ],
      [ "AXOS::detail::has_assign_into< class, class, class >", "structAXOS_1_1detail_1_1has__assign__into.html", null ],
      [ "AXOS::detail::has_contiguous< class, class >", "structAXOS_1_1detail_1_1has__contiguous.html", null ],
      [ "AXOS::detail::has_cost< class, class >", "structAXOS_1_1detail_1_1has__cost.html", null ],
      [ "AXOS::detail::has_is_contiguous< class, class >", "structAXOS_1_1detail_1_1has__is__contiguous.html", null ],
      [ "AXOS::detail::has_lvalue< class, class >", "structAXOS_1_1detail_1_1has__lvalue.html", null ],
      [ "AXOS::detail::has_packet_ok< class, class >", "structAXOS_1_1detail_1_1has__packet__ok.html", null ],
      [ "AXOS::detail::has_prepare< class, class >", "structAXOS_1_1detail_1_1has__prepare.html", null ],
      [ "AXOS::detail::has_rank< class, class >", "structAXOS_1_1detail_1_1has__rank.html", null ],
      [ "AXOS::detail::is_tensor< E >", "structAXOS_1_1detail_1_1is__tensor.html", null ],
      [ "AXOS::is_complex< T >", "structAXOS_1_1is__complex.html", null ],
      [ "AXOS::is_half< T >", "structAXOS_1_1is__half.html", null ],
      [ "AXOS::is_host_storage< S, class >", "structAXOS_1_1is__host__storage.html", null ],
      [ "AXOS::is_tensor_element< T >", "structAXOS_1_1is__tensor__element.html", null ]
    ] ],
    [ "AXOS::Solver::milp::FeasibilityJump", "classAXOS_1_1Solver_1_1milp_1_1FeasibilityJump.html", null ],
    [ "AXOS::Solver::pdlp::Fill", "structAXOS_1_1Solver_1_1pdlp_1_1Fill.html", null ],
    [ "axos_qp::Fill", "structaxos__qp_1_1Fill.html", null ],
    [ "AXOS::Solver::milp::gpu::FjData", "structAXOS_1_1Solver_1_1milp_1_1gpu_1_1FjData.html", null ],
    [ "AXOS::Solver::milp::gpu::GpuBatchLp", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1GpuBatchLp.html", null ],
    [ "AXOS::Solver::milp::gpu::GpuFeasibilityJump", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1GpuFeasibilityJump.html", null ],
    [ "AXOS::GPUMemoryPool", "classAXOS_1_1GPUMemoryPool.html", null ],
    [ "AXOS::Solver::milp::gpu::GpuProber", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1GpuProber.html", null ],
    [ "AXOS::Solver::milp::gpu::GpuPropagator", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1GpuPropagator.html", null ],
    [ "AXOS::half_fallback", "structAXOS_1_1half__fallback.html", null ],
    [ "axos_qp::Halpern", "structaxos__qp_1_1Halpern.html", null ],
    [ "AXOS::Solver::pdlp::HalpernMix", "structAXOS_1_1Solver_1_1pdlp_1_1HalpernMix.html", null ],
    [ "AXOS::Cpu::HostStorage< T >", "classAXOS_1_1Cpu_1_1HostStorage.html", null ],
    [ "AXOS::Cpu::HostStorage< double >", "classAXOS_1_1Cpu_1_1HostStorage.html", null ],
    [ "AXOS::Cpu::HostStorage< int32_t >", "classAXOS_1_1Cpu_1_1HostStorage.html", null ],
    [ "axos_qp::HprAty", "structaxos__qp_1_1HprAty.html", null ],
    [ "axos_qp::HprDual", "structaxos__qp_1_1HprDual.html", null ],
    [ "axos_qp::HprFreeQ", "structaxos__qp_1_1HprFreeQ.html", null ],
    [ "axos_qp::HprFreeXW", "structaxos__qp_1_1HprFreeXW.html", null ],
    [ "axos_qp::HprHalpern", "structaxos__qp_1_1HprHalpern.html", null ],
    [ "axos_qp::HprHalpernRed", "structaxos__qp_1_1HprHalpernRed.html", null ],
    [ "axos_qp::HprHalpernYRed", "structaxos__qp_1_1HprHalpernYRed.html", null ],
    [ "axos_qp::HprPrimal", "structaxos__qp_1_1HprPrimal.html", null ],
    [ "axos_qp::HprQb", "structaxos__qp_1_1HprQb.html", null ],
    [ "AXOS::Solver::qp::HprQp< B >", "classAXOS_1_1Solver_1_1qp_1_1HprQp.html", null ],
    [ "axos_qp::HprScalars", "structaxos__qp_1_1HprScalars.html", null ],
    [ "axos_qp::HprThetaN", "structaxos__qp_1_1HprThetaN.html", null ],
    [ "axos_qp::HprWHalf", "structaxos__qp_1_1HprWHalf.html", null ],
    [ "AXOS::Solver::Ipm< Store >", "classAXOS_1_1Solver_1_1Ipm.html", null ],
    [ "std::is_same", null, [
      [ "AXOS::is_host_storage< S, std::void_t< typename S::backend_type > >", "structAXOS_1_1is__host__storage_3_01S_00_01std_1_1void__t_3_01typename_01S_1_1backend__type_01_4_01_4.html", null ]
    ] ],
    [ "AXOS::Sparse::Kernels< Backend >", "structAXOS_1_1Sparse_1_1Kernels.html", null ],
    [ "AXOS::Sparse::Kernels< Cpu::Backend >", "structAXOS_1_1Sparse_1_1Kernels_3_01Cpu_1_1Backend_01_4.html", null ],
    [ "AXOS::Sparse::Kernels< Cuda::Backend >", "structAXOS_1_1Sparse_1_1Kernels_3_01Cuda_1_1Backend_01_4.html", null ],
    [ "AXOS::Solver::Pdlp< Store >::Kkt", "structAXOS_1_1Solver_1_1Pdlp_1_1Kkt.html", null ],
    [ "axos_qp::KktCols", "structaxos__qp_1_1KktCols.html", null ],
    [ "AXOS::Solver::pdlp::KktM", "structAXOS_1_1Solver_1_1pdlp_1_1KktM.html", null ],
    [ "AXOS::Solver::pdlp::KktN", "structAXOS_1_1Solver_1_1pdlp_1_1KktN.html", null ],
    [ "axos_qp::KktRows", "structaxos__qp_1_1KktRows.html", null ],
    [ "AXOS::Solver::LpProblem", "structAXOS_1_1Solver_1_1LpProblem.html", null ],
    [ "AXOS::Solver::LpSolution", "structAXOS_1_1Solver_1_1LpSolution.html", null ],
    [ "AXOS::Solver::qp::CpuBackend::Mat", "structAXOS_1_1Solver_1_1qp_1_1CpuBackend_1_1Mat.html", null ],
    [ "AXOS::Solver::qp::CudaBackend::Mat", "structAXOS_1_1Solver_1_1qp_1_1CudaBackend_1_1Mat.html", null ],
    [ "AXOS::Solver::MilpCheck", "structAXOS_1_1Solver_1_1MilpCheck.html", null ],
    [ "AXOS::Solver::MilpOptions", "structAXOS_1_1Solver_1_1MilpOptions.html", null ],
    [ "AXOS::Solver::MilpSolution", "structAXOS_1_1Solver_1_1MilpSolution.html", null ],
    [ "AXOS::Solver::Model", "structAXOS_1_1Solver_1_1Model.html", null ],
    [ "AXOS::Solver::milp::gpu::Module", "classAXOS_1_1Solver_1_1milp_1_1gpu_1_1Module.html", null ],
    [ "AXOS::Solver::qp::cuda_rt::Module", "classAXOS_1_1Solver_1_1qp_1_1cuda__rt_1_1Module.html", null ],
    [ "AXOS::Solver::ipm::MuAff", "structAXOS_1_1Solver_1_1ipm_1_1MuAff.html", null ],
    [ "AXOS::detail::op::Mul", "structAXOS_1_1detail_1_1op_1_1Mul.html", null ],
    [ "AXOS::Sparse::MultifrontalLdl< T, Idx >", "classAXOS_1_1Sparse_1_1MultifrontalLdl.html", null ],
    [ "AXOS::detail::op::Neg", "structAXOS_1_1detail_1_1op_1_1Neg.html", null ],
    [ "AXOS::detail::no_expr_base", "structAXOS_1_1detail_1_1no__expr__base.html", null ],
    [ "AXOS::Solver::milp::BranchAndBound::Node", "structAXOS_1_1Solver_1_1milp_1_1BranchAndBound_1_1Node.html", null ],
    [ "AXOS::Solver::NormalKkt", "classAXOS_1_1Solver_1_1NormalKkt.html", null ],
    [ "AXOS::Solver::qp::cuda_rt::Nvrtc", "structAXOS_1_1Solver_1_1qp_1_1cuda__rt_1_1Nvrtc.html", null ],
    [ "AXOS::Solver::Presolve::Op", "structAXOS_1_1Solver_1_1Presolve_1_1Op.html", null ],
    [ "AXOS::Solver::Options", "structAXOS_1_1Solver_1_1Options.html", null ],
    [ "AXOS::simd::Pack< T >", "structAXOS_1_1simd_1_1Pack.html", null ],
    [ "AXOS::Solver::ipm::PackRhs", "structAXOS_1_1Solver_1_1ipm_1_1PackRhs.html", null ],
    [ "AXOS::Solver::Parallel< Backend >", "structAXOS_1_1Solver_1_1Parallel.html", null ],
    [ "AXOS::Solver::Parallel< Cpu::Backend >", "structAXOS_1_1Solver_1_1Parallel_3_01Cpu_1_1Backend_01_4.html", null ],
    [ "AXOS::Solver::Parallel< Cuda::Backend >", "structAXOS_1_1Solver_1_1Parallel_3_01Cuda_1_1Backend_01_4.html", null ],
    [ "axos_qp::PdCgCurv", "structaxos__qp_1_1PdCgCurv.html", null ],
    [ "axos_qp::PdCgDir", "structaxos__qp_1_1PdCgDir.html", null ],
    [ "axos_qp::PdCgStep", "structaxos__qp_1_1PdCgStep.html", null ],
    [ "axos_qp::PdDual", "structaxos__qp_1_1PdDual.html", null ],
    [ "axos_qp::PdHalpernN", "structaxos__qp_1_1PdHalpernN.html", null ],
    [ "AXOS::Solver::qp::Pdhcg< B >", "classAXOS_1_1Solver_1_1qp_1_1Pdhcg.html", null ],
    [ "axos_qp::PdKktCols", "structaxos__qp_1_1PdKktCols.html", null ],
    [ "AXOS::Solver::Pdlp< Store >", "classAXOS_1_1Solver_1_1Pdlp.html", null ],
    [ "axos_qp::PdPgStep", "structaxos__qp_1_1PdPgStep.html", null ],
    [ "axos_qp::PdPgUpdate", "structaxos__qp_1_1PdPgUpdate.html", null ],
    [ "axos_qp::PdStart", "structaxos__qp_1_1PdStart.html", null ],
    [ "AXOS::la_detail::PermCache< T >", "structAXOS_1_1la__detail_1_1PermCache.html", null ],
    [ "AXOS::PermOp", "structAXOS_1_1PermOp.html", null ],
    [ "AXOS::Sparse::MultifrontalLdl< T, Idx >::Pool", "structAXOS_1_1Sparse_1_1MultifrontalLdl_1_1Pool.html", null ],
    [ "AXOS::Sparse::cuda_detail::PoolBuf", "structAXOS_1_1Sparse_1_1cuda__detail_1_1PoolBuf.html", null ],
    [ "AXOS::detail::PoolReaper", "structAXOS_1_1detail_1_1PoolReaper.html", null ],
    [ "AXOS::detail::PoolSlot", "structAXOS_1_1detail_1_1PoolSlot.html", null ],
    [ "AXOS::Solver::Presolve", "classAXOS_1_1Solver_1_1Presolve.html", null ],
    [ "AXOS::Solver::PresolveOptions", "structAXOS_1_1Solver_1_1PresolveOptions.html", null ],
    [ "AXOS::Solver::pdlp::PrimalRayM", "structAXOS_1_1Solver_1_1pdlp_1_1PrimalRayM.html", null ],
    [ "AXOS::Solver::pdlp::PrimalRayN", "structAXOS_1_1Solver_1_1pdlp_1_1PrimalRayN.html", null ],
    [ "AXOS::Solver::milp::gpu::ProbeData", "structAXOS_1_1Solver_1_1milp_1_1gpu_1_1ProbeData.html", null ],
    [ "AXOS::Solver::milp::gpu::ProbeResult", "structAXOS_1_1Solver_1_1milp_1_1gpu_1_1ProbeResult.html", null ],
    [ "AXOS::Solver::milp::ProbingStats", "structAXOS_1_1Solver_1_1milp_1_1ProbingStats.html", null ],
    [ "AXOS::Sparse::MultifrontalLdl< T, Idx >::Profile", "structAXOS_1_1Sparse_1_1MultifrontalLdl_1_1Profile.html", null ],
    [ "AXOS::Solver::milp::Propagator", "classAXOS_1_1Solver_1_1milp_1_1Propagator.html", null ],
    [ "AXOS::Solver::qp::QpIpm", "classAXOS_1_1Solver_1_1qp_1_1QpIpm.html", null ],
    [ "AXOS::Solver::QpOptions", "structAXOS_1_1Solver_1_1QpOptions.html", null ],
    [ "AXOS::Solver::QpProblem", "structAXOS_1_1Solver_1_1QpProblem.html", null ],
    [ "AXOS::Solver::qp::QpReduction", "structAXOS_1_1Solver_1_1qp_1_1QpReduction.html", null ],
    [ "AXOS::Solver::QpScaling", "structAXOS_1_1Solver_1_1QpScaling.html", null ],
    [ "AXOS::Solver::QpSolution", "structAXOS_1_1Solver_1_1QpSolution.html", null ],
    [ "AXOS::la_detail::QrPanel< T >", "structAXOS_1_1la__detail_1_1QrPanel.html", null ],
    [ "AXOS::Solver::QuadEntry", "structAXOS_1_1Solver_1_1QuadEntry.html", null ],
    [ "AXOS::detail::rank_from< L, R, class >", "structAXOS_1_1detail_1_1rank__from.html", null ],
    [ "AXOS::detail::rank_from< E >", "structAXOS_1_1detail_1_1rank__from.html", [
      [ "AXOS::ScalarExpr< T, E, Op, Left >", "classAXOS_1_1ScalarExpr.html", null ],
      [ "AXOS::UnaryExpr< T, E, F >", "classAXOS_1_1UnaryExpr.html", null ]
    ] ],
    [ "AXOS::detail::rank_from< L, R >", "structAXOS_1_1detail_1_1rank__from.html", [
      [ "AXOS::BinaryExpr< T, L, R, Op >", "classAXOS_1_1BinaryExpr.html", null ]
    ] ],
    [ "AXOS::detail::rank_from< L, R, std::enable_if_t< has_rank< L >::value > >", "structAXOS_1_1detail_1_1rank__from_3_01L_00_01R_00_01std_1_1enable__if__t_3_01has__rank_3_01L_01_4_1_1value_01_4_01_4.html", null ],
    [ "AXOS::detail::rank_from< L, R, std::enable_if_t<!has_rank< L >::value &&!std::is_void_v< R > &&has_rank< R >::value > >", "structAXOS_1_1detail_1_1rank__from_3_01L_00_01R_00_01std_1_1enable__if__t_3_9has__rank_3_01L_01_21fb3dcd81489c1303c4a670c97ca470.html", null ],
    [ "AXOS::Sparse::real_of< T >", "structAXOS_1_1Sparse_1_1real__of.html", null ],
    [ "AXOS::Sparse::real_of< std::complex< R > >", "structAXOS_1_1Sparse_1_1real__of_3_01std_1_1complex_3_01R_01_4_01_4.html", null ],
    [ "AXOS::real_type< T >", "structAXOS_1_1real__type.html", null ],
    [ "AXOS::real_type< std::complex< R > >", "structAXOS_1_1real__type_3_01std_1_1complex_3_01R_01_4_01_4.html", null ],
    [ "AXOS::Solver::ipm::Recenter", "structAXOS_1_1Solver_1_1ipm_1_1Recenter.html", null ],
    [ "AXOS::Solver::ipm::RefineRes", "structAXOS_1_1Solver_1_1ipm_1_1RefineRes.html", null ],
    [ "AXOS::Solver::ipm::ResD", "structAXOS_1_1Solver_1_1ipm_1_1ResD.html", null ],
    [ "AXOS::Solver::ipm::ResP", "structAXOS_1_1Solver_1_1ipm_1_1ResP.html", null ],
    [ "AXOS::Solver::Result", "structAXOS_1_1Solver_1_1Result.html", null ],
    [ "axos_qp::Scale", "structaxos__qp_1_1Scale.html", null ],
    [ "AXOS::Solver::pdlp::ScaleCopy", "structAXOS_1_1Solver_1_1pdlp_1_1ScaleCopy.html", null ],
    [ "axos_qp::ScaleNorm", "structaxos__qp_1_1ScaleNorm.html", null ],
    [ "AXOS::Solver::Scaling", "structAXOS_1_1Solver_1_1Scaling.html", null ],
    [ "AXOS::Solver::ipm::ScatterKkt", "structAXOS_1_1Solver_1_1ipm_1_1ScatterKkt.html", null ],
    [ "AXOS::kernels::blas_detail::Scratch< T >", "classAXOS_1_1kernels_1_1blas__detail_1_1Scratch.html", null ],
    [ "AXOS::detail::SerialScope", "structAXOS_1_1detail_1_1SerialScope.html", null ],
    [ "AXOS::Solver::SimplexBasis", "structAXOS_1_1Solver_1_1SimplexBasis.html", null ],
    [ "AXOS::Solver::SolverOptions", "structAXOS_1_1Solver_1_1SolverOptions.html", null ],
    [ "AXOS::Sparse::SparseLdlt< T, Idx, Store >", "classAXOS_1_1Sparse_1_1SparseLdlt.html", null ],
    [ "AXOS::Sparse::SparseLdlt< double, int32_t, Cpu::HostStorage >", "classAXOS_1_1Sparse_1_1SparseLdlt.html", null ],
    [ "AXOS::Sparse::SparseLdlt< T, Idx, Cpu::HostStorage >", "classAXOS_1_1Sparse_1_1SparseLdlt_3_01T_00_01Idx_00_01Cpu_1_1HostStorage_01_4.html", null ],
    [ "AXOS::Sparse::SparseLdlt< T, Idx, Cuda::CudaStorage >", "classAXOS_1_1Sparse_1_1SparseLdlt_3_01T_00_01Idx_00_01Cuda_1_1CudaStorage_01_4.html", null ],
    [ "AXOS::Solver::ipm::SqNorm", "structAXOS_1_1Solver_1_1ipm_1_1SqNorm.html", null ],
    [ "AXOS::Solver::pdlp::SqNormN", "structAXOS_1_1Solver_1_1pdlp_1_1SqNormN.html", null ],
    [ "AXOS::detail::op::Sqrt", "structAXOS_1_1detail_1_1op_1_1Sqrt.html", null ],
    [ "AXOS::Solver::Pdlp< Store >::Start", "structAXOS_1_1Solver_1_1Pdlp_1_1Start.html", null ],
    [ "AXOS::GPUMemoryPool::Stats", "structAXOS_1_1GPUMemoryPool_1_1Stats.html", null ],
    [ "AXOS::Solver::ipm::Stats", "structAXOS_1_1Solver_1_1ipm_1_1Stats.html", null ],
    [ "AXOS::Solver::ipm::StepD", "structAXOS_1_1Solver_1_1ipm_1_1StepD.html", null ],
    [ "AXOS::Solver::pdlp::StepDiffM", "structAXOS_1_1Solver_1_1pdlp_1_1StepDiffM.html", null ],
    [ "AXOS::Solver::pdlp::StepDiffN", "structAXOS_1_1Solver_1_1pdlp_1_1StepDiffN.html", null ],
    [ "AXOS::Solver::ipm::StepP", "structAXOS_1_1Solver_1_1ipm_1_1StepP.html", null ],
    [ "axos_qp::Store", "structaxos__qp_1_1Store.html", null ],
    [ "AXOS::detail::op::Sub", "structAXOS_1_1detail_1_1op_1_1Sub.html", null ],
    [ "AXOS::Solver::milp::CmirSeparator::Sub", "structAXOS_1_1Solver_1_1milp_1_1CmirSeparator_1_1Sub.html", null ],
    [ "AXOS::Solver::qp::qipm::SubVec", "structAXOS_1_1Solver_1_1qp_1_1qipm_1_1SubVec.html", null ],
    [ "AXOS::Solver::SVec", "structAXOS_1_1Solver_1_1SVec.html", null ],
    [ "detail::tensor_base_t", null, [
      [ "AXOS::tensorET< 2, T >", "classAXOS_1_1tensorET.html", null ],
      [ "AXOS::tensorET< 1, double, Cpu::HostStorage< double > >", "classAXOS_1_1tensorET.html", null ],
      [ "AXOS::tensorET< 1, double, Cuda::CudaStorage< double > >", "classAXOS_1_1tensorET.html", null ],
      [ "AXOS::tensorET< 1, int32_t, Cuda::CudaStorage< int32_t > >", "classAXOS_1_1tensorET.html", null ],
      [ "AXOS::tensorET< DIM, T, Storage >", "classAXOS_1_1tensorET.html", null ]
    ] ],
    [ "AXOS::Solver::milp::Trail", "structAXOS_1_1Solver_1_1milp_1_1Trail.html", null ],
    [ "std::true_type", null, [
      [ "AXOS::Sparse::is_complex_value< std::complex< R > >", "structAXOS_1_1Sparse_1_1is__complex__value_3_01std_1_1complex_3_01R_01_4_01_4.html", null ],
      [ "AXOS::detail::has_assign_into< E, T, std::void_t< decltype(std::declval< const E & >().assign_into(std::declval< T * >()))> >", "structAXOS_1_1detail_1_1has__assign__into_3_01E_00_01T_00_01std_1_1void__t_3_01decltype_07std_1_a9a72286143dc5a775e913f958e6f8b9.html", null ],
      [ "AXOS::detail::has_contiguous< E, std::void_t< decltype(std::declval< const E & >().contiguous())> >", "structAXOS_1_1detail_1_1has__contiguous_3_01E_00_01std_1_1void__t_3_01decltype_07std_1_1declval_6bb7d1b4f84a0ca76812e554c0c6d373.html", null ],
      [ "AXOS::detail::has_cost< E, std::void_t< decltype(E::cost)> >", "structAXOS_1_1detail_1_1has__cost_3_01E_00_01std_1_1void__t_3_01decltype_07E_1_1cost_08_4_01_4.html", null ],
      [ "AXOS::detail::has_is_contiguous< X, std::void_t< decltype(std::declval< const X & >().is_contiguous())> >", "structAXOS_1_1detail_1_1has__is__contiguous_3_01X_00_01std_1_1void__t_3_01decltype_07std_1_1decl507b5babbac60f9452cb414a394d48b1.html", null ],
      [ "AXOS::detail::has_lvalue< E, std::void_t< decltype(std::declval< const E & >().lvalue(size_t(0)))> >", "structAXOS_1_1detail_1_1has__lvalue_3_01E_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_01114de5661a9db3f1aff74aafcb398fe7.html", null ],
      [ "AXOS::detail::has_packet_ok< E, std::void_t< decltype(E::packet_ok)> >", "structAXOS_1_1detail_1_1has__packet__ok_3_01E_00_01std_1_1void__t_3_01decltype_07E_1_1packet__ok_08_4_01_4.html", null ],
      [ "AXOS::detail::has_prepare< E, std::void_t< decltype(std::declval< const E & >().prepare())> >", "structAXOS_1_1detail_1_1has__prepare_3_01E_00_01std_1_1void__t_3_01decltype_07std_1_1declval_3_04d5f5d1c894897d35bf3a91498160d6c.html", null ],
      [ "AXOS::detail::has_rank< E, std::void_t< decltype(E::rank)> >", "structAXOS_1_1detail_1_1has__rank_3_01E_00_01std_1_1void__t_3_01decltype_07E_1_1rank_08_4_01_4.html", null ],
      [ "AXOS::detail::is_tensor< tensorET< D, T, S > >", "structAXOS_1_1detail_1_1is__tensor_3_01tensorET_3_01D_00_01T_00_01S_01_4_01_4.html", null ],
      [ "AXOS::is_complex< std::complex< R > >", "structAXOS_1_1is__complex_3_01std_1_1complex_3_01R_01_4_01_4.html", null ],
      [ "AXOS::is_half< half_fallback >", "structAXOS_1_1is__half_3_01half__fallback_01_4.html", null ],
      [ "AXOS::is_tensor_element< double >", "structAXOS_1_1is__tensor__element_3_01double_01_4.html", null ],
      [ "AXOS::is_tensor_element< float >", "structAXOS_1_1is__tensor__element_3_01float_01_4.html", null ],
      [ "AXOS::is_tensor_element< half_fallback >", "structAXOS_1_1is__tensor__element_3_01half__fallback_01_4.html", null ],
      [ "AXOS::is_tensor_element< std::complex< double > >", "structAXOS_1_1is__tensor__element_3_01std_1_1complex_3_01double_01_4_01_4.html", null ],
      [ "AXOS::is_tensor_element< std::complex< float > >", "structAXOS_1_1is__tensor__element_3_01std_1_1complex_3_01float_01_4_01_4.html", null ],
      [ "AXOS::is_tensor_element< std::int32_t >", "structAXOS_1_1is__tensor__element_3_01std_1_1int32__t_01_4.html", null ],
      [ "AXOS::is_tensor_element< std::int64_t >", "structAXOS_1_1is__tensor__element_3_01std_1_1int64__t_01_4.html", null ]
    ] ],
    [ "AXOS::detail::type_identity< T >", "structAXOS_1_1detail_1_1type__identity.html", null ],
    [ "AXOS::Solver::ipm::Unpack", "structAXOS_1_1Solver_1_1ipm_1_1Unpack.html", null ],
    [ "AXOS::Solver::ipm::UpdatePrimalDual", "structAXOS_1_1Solver_1_1ipm_1_1UpdatePrimalDual.html", null ],
    [ "AXOS::Solver::milp::CmirSeparator::VB", "structAXOS_1_1Solver_1_1milp_1_1CmirSeparator_1_1VB.html", null ],
    [ "AXOS::Sparse::dense::packed::vd", "structAXOS_1_1Sparse_1_1dense_1_1packed_1_1vd.html", null ],
    [ "AXOS::Solver::milp::BranchAndBound::WorseBound", "structAXOS_1_1Solver_1_1milp_1_1BranchAndBound_1_1WorseBound.html", null ],
    [ "AXOS::Solver::pdlp::WSqNorm", "structAXOS_1_1Solver_1_1pdlp_1_1WSqNorm.html", null ],
    [ "AXOS::Solver::pdlp::XUpdate", "structAXOS_1_1Solver_1_1pdlp_1_1XUpdate.html", null ],
    [ "AXOS::Solver::pdlp::XUpdateStep", "structAXOS_1_1Solver_1_1pdlp_1_1XUpdateStep.html", null ],
    [ "AXOS::Solver::pdlp::YUpdate", "structAXOS_1_1Solver_1_1pdlp_1_1YUpdate.html", null ],
    [ "AXOS::Solver::pdlp::YUpdateStep", "structAXOS_1_1Solver_1_1pdlp_1_1YUpdateStep.html", null ]
];